export default [
    "Unlocking the Secrets to a Productive Morning Routine",
    "Streamlining Your Daily Tasks with Simple Life Hacks",
    "Time Management Tips for a Stress-Free Life",
    "Organizing Your Space for Maximum Efficiency",
    "Mastering the Art of Goal Setting in Your Personal Life",
    "A Journey through Hidden Gems: Off-the-Beaten-Path Destinations",
    "Exploring Exotic Cuisine Around the World",
    "Backpacking 101: Tips for the Ultimate Adventure",
    "Adventures in Solo Travel: Discovering Yourself on the Road",
    "Capturing Moments: Photography Tips for Travel Enthusiasts",
    "The Rise of AI: Navigating the Future of Technology",
    "Exploring Augmented Reality Applications in Everyday Life",
    "Cybersecurity Essentials for the Modern Internet User",
    "The Impact of 5G on the Tech Landscape",
    "Unveiling the Latest Gadgets and Gizmos of the Year",
    "Mindfulness Meditation: A Guide to Inner Peace",
    "Healthy Habits for a Balanced Lifestyle",
    "The Science of Sleep: Tips for a Restful Night",
    "Superfoods and Their Benefits for Overall Wellbeing",
    "Finding Joy in Exercise: Transforming Your Fitness Routine",
    "Nurturing Your Creative Spirit: Tips for Artists and Writers",
    "Breaking Through Creative Blocks: Strategies for Success",
    "DIY Projects to Spark Your Imagination",
    "Cultivating a Creative Mindset in a Tech-Driven World",
    "Exploring Unconventional Art Forms and Expressions",
];
  